# The addresses and ports to bind the server to
binds:
    - { address: '127.0.0.1', port: 53 }
    - { address: '168.235.68.44', port: 53 }
    - { address: '168.235.68.45', port: 53 }
    - { address: '[2604:180:2:4f4::2]', port: 53 }
    - { address: '[2604:180:2:4f4::3]', port: 53 }
# The file to log queries to
log: 'server.log'
# The main control domain used for tracking
control: 'bitfl1p.com'
# The contact email for MX and TXT records
contact: 'luke@hydrantlabs.org'
# The BitFlipped Domains to answer and the corresponding correct value
questions:
    apple.com:
        - 'applg.com'
    cloudfront.net:
        - 'aloudfront.net'
        - 'bloudfront.net'
        - 'cdoudfront.net'
        - 'clgudfront.net'
        - 'clkudfront.net'
        - 'clmudfront.net'
        - 'clnudfront.net'
        - 'clo5dfront.net'
        - 'cloqdfront.net'
        - 'choudfront.net'
        - 'clotdfront.net'
        - 'cloudbront.net'
        - 'cloudf2ont.net'
        - 'cloudfbont.net'
        - 'cloudfpont.net'
        - 'cloudfrgnt.net'
        - 'cloudfrknt.net'
        - 'cloudfrmnt.net'
        - 'cloudfrnnt.net'
        - 'cloudfroft.net'
        - 'cloudfrojt.net'
        - 'cloudfrolt.net'
        - 'cloudfron4.net'
        - 'cloudfrond.net'
        - 'cloudfronp.net'
        - 'cloudfronu.net'
        - 'cloudfronv.net'
        - 'cloudfroot.net'
        - 'cloudfsont.net'
        - 'cloudfvont.net'
        - 'cloudfzont.net'
        - 'cloudnront.net'
        - 'cloudvront.net'
        - 'clouefront.net'
        - 'cloulfront.net'
        - 'cmoudfront.net'
        - 'cnoudfront.net'
        - 'kloudfront.net'
        - 'sloudfront.net'
    doubleclick.net:
        - 'dgubleclick.net'
        - 'dkubleclick.net'
        - 'dnubleclick.net'
        - 'dmubleclick.net'
        - 'doqbleclick.net'
        - 'dotbleclick.net'
        - 'doublecliak.net'
        - 'doubleblick.net'
        - 'doubleclibk.net'
        - 'doublecligk.net'
        - 'doubleclicc.net'
        - 'doubleclikk.net'
        - 'doubleclisk.net'
        - 'doubleclmck.net'
        - 'doublecnick.net'
        - 'doublecmick.net'
        - 'doublmclick.net'
        - 'doubleglick.net'
        - 'doubluclick.net'
        - 'doubmeclick.net'
        - 'doubneclick.net'
        - 'doucleclick.net'
        - 'doufleclick.net'
        - 'doujleclick.net'
        - 'dowbleclick.net'
        - 'dourleclick.net'
    google-analytics.com:
        - 'googlm-analytics.com'
        - 'googlg-analytics.com'
        - 'googne-analytics.com'
        - 'gooole-analytics.com'
        - 'ggogle-analytics.com'
        - 'gmogle-analytics.com'
        - 'gomgle-analytics.com'
        - 'gooele-analytics.com'
        - 'googde-analytics.com'
        - 'google-alalytics.com'
    googleapis.com:
        - 'coogleapis.com'
        - 'eoogleapis.com'
        - 'ggogleapis.com'
        - 'gkogleapis.com'
        - 'gmogleapis.com'
        - 'gnogleapis.com'
        - 'goggleapis.com'
        - 'gokgleapis.com'
        - 'gomgleapis.com'
        - 'goocleapis.com'
        - 'gooeleapis.com'
        - 'googdeapis.com'
        - 'googheapis.com'
        - 'googldapis.com'
        - 'googlgapis.com'
        - 'googlmapis.com'
        - 'googmeapis.com'
        - 'googneapis.com'
        - 'goowleapis.com'
        - 'goooleapis.com'
        - 'ooogleapis.com'
        - 'woogleapis.com'
    googleusercontent.com:
        - 'goggleusercontent.com'
        - 'coogleusercontent.com'
        - 'eoogleusercontent.com'
        - 'ggogleusercontent.com'
        - 'gkogleusercontent.com'
        - 'gmogleusercontent.com'
        - 'gnogleusercontent.com'
        - 'gokgleusercontent.com'
        - 'gomgleusercontent.com'
        - 'gongleusercontent.com'
        - 'goocleusercontent.com'
        - 'gooeleusercontent.com'
        - 'googdeusercontent.com'
        - 'googheusercontent.com'
        - 'googlausercontent.com'
        - 'googldusercontent.com'
        - 'google5sercontent.com'
        - 'googleqsercontent.com'
        - 'googletsercontent.com'
        - 'googleu3ercontent.com'
        - 'googleucercontent.com'
        - 'googleuqercontent.com'
        - 'googleurercontent.com'
        - 'googleusdrcontent.com'
        - 'googleuse2content.com'
        - 'googleusepcontent.com'
        - 'googleuseraontent.com'
        - 'googleuserbontent.com'
        - 'googleusercgntent.com'
        - 'googleuserckntent.com'
        - 'googleusercmntent.com'
        - 'googleusercnntent.com'
        - 'googleusercoftent.com'
        - 'googleusercojtent.com'
        - 'googleusercoltent.com'
        - 'googleusercon4ent.com'
        - 'googleusercondent.com'
        - 'googleuserconpent.com'
        - 'googleusercontdnt.com'
        - 'googleuserconteft.com'
        - 'googleusercontejt.com'
        - 'googleusercontelt.com'
        - 'googleuserconten4.com'
        - 'googleusercontend.com'
        - 'googleusercontenp.com'
        - 'googleusercontenu.com'
        - 'googleusercontenv.com'
        - 'googleuserconteot.com'
        - 'googleusercontgnt.com'
        - 'googleusercontmnt.com'
        - 'googleusercontunt.com'
        - 'googleuserconuent.com'
        - 'googleuserconvent.com'
        - 'googleusergontent.com'
        - 'googleuserkontent.com'
        - 'googleusersontent.com'
        - 'googleusescontent.com'
        - 'googleusevcontent.com'
        - 'googleusezcontent.com'
        - 'googleusgrcontent.com'
        - 'googleusmrcontent.com'
        - 'googleusurcontent.com'
        - 'googleuwercontent.com'
        - 'googlewsercontent.com'
        - 'googlgusercontent.com'
        - 'googlmusercontent.com'
        - 'googluusercontent.com'
        - 'googmeusercontent.com'
        - 'googneusercontent.com'
        - 'goooleusercontent.com'
        - 'goowleusercontent.com'
        - 'woogleusercontent.com'
    gstatic.com:
        - 'gs4atic.com'
        - 'gsdatic.com'
        - 'gspatic.com'
        - 'gsta4ic.com'
        - 'gstadic.com'
        - 'gstapic.com'
        - 'gstathc.com'
        - 'gstatia.com'
        - 'gstatib.com'
        - 'gstatig.com'
        - 'gstatkc.com'
        - 'gstatmc.com'
        - 'gstatyc.com'
        - 'gstavic.com'
        - 'gstauic.com'
        - 'gstctic.com'
        - 'gstqtic.com'
        - 'gsuatic.com'
        - 'gsvatic.com'
    icloud.com:
        - 'iclotd.com'
        - 'iclgud.com'
        - 'icdoud.com'
        - 'iclkud.com'
        - 'iclmud.com'
        - 'iclnud.com'
        - 'icloqd.com'
        - 'icnoud.com'
    amazonaws.com:
        - 'amazonass.com'
    s3.amazonaws.com:
        - 's3namazonaws.com'
    compute-1.amazonaws.com:
        - 'compute-1namazonaws.com'
    compute-2.amazonaws.com:
        - 'compute-2namazonaws.com'
    elb.amazonaws.com:
        - 'elbnamazonaws.com'
    disqus.com:
        - 'dhsqus.com'
        - 'di3qus.com'
        - 'diqqus.com'
        - 'dirqus.com'
        - 'dis1us.com'
        - 'disaus.com'
        - 'disqqs.com'
        - 'disq5s.com'
        - 'disqts.com'
        - 'disqu3.com'
        - 'disquc.com'
        - 'disquq.com'
        - 'disqur.com'
        - 'disquw.com'
        - 'disqws.com'
        - 'disuus.com'
        - 'diwqus.com'
        - 'disyus.com'
        - 'dksqus.com'
        - 'dmsqus.com'
        - 'eisqus.com'
        - 'dysqus.com'
        - 'tisqus.com'
        - 'lisqus.com'
    jquery.com:
        - 'jauery.com'
        - 'jqqery.com'
        - 'jpuery.com'
        - 'jqtery.com'
        - 'jqueby.com'
        - 'jquepy.com'
        - 'jquerq.com'
        - 'jquerx.com'
        - 'jquesy.com'
        - 'jquevy.com'
        - 'jqugry.com'
        - 'jquezy.com'
        - 'jqumry.com'
        - 'jsuery.com'
        - 'juuery.com'
    ytimg.com:
        - 'ytieg.com'
        - 'yti-g.com'
        - 'y4img.com'
    twimg.com:
        - '4wimg.com'
        - 't7img.com'
        - 'twhmg.com'
        - 'twi-g.com'
        - 'twimw.com'
        - 'twilg.com'
        - 'twkmg.com'
        - 'twmmg.com'
        - 'uwimg.com'
    aspnetcdn.com:
        - 'a3pnetcdn.com'
        - 'acpnetcdn.com'
        - 'arpnetcdn.com'
        - 'aqpnetcdn.com'
        - 'as0netcdn.com'
        - 'aspfetcdn.com'
        - 'aspjetcdn.com'
        - 'aspndtcdn.com'
        - 'aspletcdn.com'
        - 'aspne4cdn.com'
        - 'aspnedcdn.com'
        - 'aspnepcdn.com'
        - 'aspnetadn.com'
        - 'aspnetbdn.com'
        - 'aspnetcdf.com'
        - 'aspnetcdj.com'
        - 'aspnetcdl.com'
        - 'aspnetcdo.com'
        - 'aspnetcen.com'
        - 'aspnetcln.com'
        - 'aspnetctn.com'
        - 'aspnetgdn.com'
        - 'aspnetkdn.com'
        - 'aspnetsdn.com'
        - 'aspneucdn.com'
        - 'aspnevcdn.com'
        - 'aspngtcdn.com'
        - 'aspoetcdn.com'
        - 'aspnmtcdn.com'
        - 'asqnetcdn.com'
        - 'asrnetcdn.com'
        - 'astnetcdn.com'
        - 'awpnetcdn.com'
        - 'asxnetcdn.com'
        - 'espnetcdn.com'
        - 'cspnetcdn.com'
        - 'qspnetcdn.com'
        - 'ispnetcdn.com'
    sfdcstatic.com:
        - '3fdcstatic.com'
        - 'cfdcstatic.com'
        - 'qfdcstatic.com'
        - 'rfdcstatic.com'
        - 'sbdcstatic.com'
        - 'sfdbstatic.com'
        - 'sfdcrtatic.com'
        - 'sfdcqtatic.com'
        - 'sfdastatic.com'
        - 'sfdcctatic.com'
        - 'sfdc3tatic.com'
        - 'sfdcsdatic.com'
        - 'sfdcs4atic.com'
        - 'sfdcsta4ic.com'
        - 'sfdcstadic.com'
        - 'sfdcstatia.com'
        - 'sfdcspatic.com'
        - 'sfdcstathc.com'
        - 'sfdcstapic.com'
        - 'sfdcstatib.com'
        - 'sfdcstatis.com'
        - 'sfdcstavic.com'
        - 'sfdcstatyc.com'
        - 'sfdcstauic.com'
        - 'sfdcstatik.com'
        - 'sfdcstatig.com'
        - 'sfdcstatkc.com'
        - 'sfdcstatmc.com'
        - 'sfdcstctic.com'
        - 'sfdcstqtic.com'
        - 'sfdcsvatic.com'
        - 'sfdcsuatic.com'
        - 'sfdcwtatic.com'
        - 'sfdkstatic.com'
        - 'sfdgstatic.com'
        - 'sfecstatic.com'
        - 'sfdsstatic.com'
        - 'sflcstatic.com'
        - 'sftcstatic.com'
        - 'sndcstatic.com'
        - 'svdcstatic.com'
        - 'wfdcstatic.com'
    fbcdn.net:
        - 'fbadn.net'
        - 'fbcdj.net'
        - 'frcdn.net'

# The different responses
answers:
    # The BitFlipped response
    flipped:
        a: '168.235.68.44'
        aaaa: '[2604:180:2:4f4::2]'
    # The UnFlipped response
    correct:
        a: '168.235.68.45'
        aaaa: '[2604:180:2:4f4::3]'
